// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6nIpzrO2PN0gPBH6DmNtJGcL3jOomr4s',
    appId: '1:926516087972:web:c4a449576512c807b42a31',
    messagingSenderId: '926516087972',
    projectId: 'sivailks',
    authDomain: 'sivailks.firebaseapp.com',
    storageBucket: 'sivailks.firebasestorage.app',
    measurementId: 'G-8KJNLQV0BQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALP5Jwio9iL2-PNo2en94PK-AyS8c0j7c',
    appId: '1:926516087972:android:cebef5f317a1517cb42a31',
    messagingSenderId: '926516087972',
    projectId: 'sivailks',
    storageBucket: 'sivailks.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiexHGbvDsCqafmfWdKvp9Bf0knPSv5to',
    appId: '1:926516087972:ios:46a8ddc36968d0eeb42a31',
    messagingSenderId: '926516087972',
    projectId: 'sivailks',
    storageBucket: 'sivailks.firebasestorage.app',
    iosBundleId: 'com.example.fashionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiexHGbvDsCqafmfWdKvp9Bf0knPSv5to',
    appId: '1:926516087972:ios:46a8ddc36968d0eeb42a31',
    messagingSenderId: '926516087972',
    projectId: 'sivailks',
    storageBucket: 'sivailks.firebasestorage.app',
    iosBundleId: 'com.example.fashionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6nIpzrO2PN0gPBH6DmNtJGcL3jOomr4s',
    appId: '1:926516087972:web:301793de47a63d37b42a31',
    messagingSenderId: '926516087972',
    projectId: 'sivailks',
    authDomain: 'sivailks.firebaseapp.com',
    storageBucket: 'sivailks.firebasestorage.app',
    measurementId: 'G-PHVR89EFX4',
  );
}
